In [9]:
import pandas as pd

In [79]:
tags_df = pd.read_csv('tags.csv')
tags_df.head()

   userId  movieId                      tag   timestamp
0      15      339  sandra 'boring' bullock  1138537770
1      15     1955                  dentist  1193435061
2      15     7478                 Cambodia  1170560997
3      15    32892                  Russian  1170626366
4      15    34162              forgettable  1141391765

In [72]:
grouped_tags = tags_df.groupby('movieId')['tag'].apply(lambda x:', '.join(x)).reset_index()

grouped_tags.head()

   movieId                                                tag
0        1                                              Pixar
1        5                                       steve martin
2       47  biblical, crime, dark, disturbing, greed, horr...
3       50                                           thriller
4      104                                       adam sandler

In [75]:
rating_df = pd.read_csv('ratings.csv')
rating_grouped = rating_df.groupby('movieId')['rating'].mean().reset_index()
rating_grouped.head()

   movieId    rating
0        1  3.920930
1        2  3.431818
2        3  3.259615
3        4  2.357143
4        5  3.071429

In [76]:
rating_tag = rating_grouped.merge(grouped_tags, on ='movieId', how='left')
rating_tag.head()

   movieId    rating           tag
0        1  3.920930         Pixar
1        2  3.431818           NaN
2        3  3.259615           NaN
3        4  2.357143           NaN
4        5  3.071429  steve martin

In [77]:
movies_df = pd.read_csv('movies.csv')
movies_df.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [80]:
movies_rating_tag = movies_df.merge(rating_tag, on ='movieId', how='left')
movies_rating_tag.head(15)

,movieId,title,genres,rating,tag
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,3.920930,Pixar
1,2,Jumanji (1995),Adventure|Children|Fantasy,3.431818,NaN
2,3,Grumpier Old Men (1995),Comedy|Romance,3.259615,NaN
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance,2.357143,NaN
4,5,Father of the Bride Part II (1995),Comedy,3.071429,steve martin
5,6,Heat (1995),Action|Crime|Thriller,3.946078,NaN
6,7,Sabrina (1995),Comedy|Romance,3.185185,NaN
7,8,Tom and Huck (1995),Adventure|Children,2.875000,NaN
8,9,Sudden Death (1995),Action,3.125000,NaN
9,10,GoldenEye (1995),Action|Adventure|Thriller,3.496212,NaN
10,11,"American President, The (1995)",Comedy|Drama|Romance,3.671429,NaN
11,12,Dracula: Dead and Loving It (1995),Comedy|Horror,2.421053,NaN
12,13,Balto (1995),Adventure|Animation|Children,3.125000,NaN
13,14,Nixon (1995),Drama,3.833333,NaN
14,15,Cutthroat Island (1995),Action|Adventure|Romance,3.000000,NaN

In [82]:
movies_rating_tag.to_excel('testing_write.xlsx', sheet_name='Получилось')